### ISSUE TITLE
OpenSpy master often down

### ISSUE THREAD

**Issue by BestNoob** [devzspy/Openspy-Core#2]
OpenSpy seems to be very often down. Can someone fix this ? I think this is the best solution and very easy to use for Server and Client but it is not usable when the OpenSpy master is all the time down.

https://www.moddb.com/games/crysis/downloads/crysis-multiplayer-openspy-net-fix

https://www.moddb.com/mods/worms-4-mayhem-openspy-patch/downloads/worms-4-mayhem-openspy-patch

Greeds 
BestNoob

**Comment by devzspy** [comment]
This isnt the official repo for OpenSpy. Just a copy of the working peerchat IRC services.
