### ISSUE TITLE
Peerchat does not working

### ISSUE THREAD

**Issue by jackcaver** [devzspy/Openspy-Core#6]
when i trying to connect it gives this error: "Peerchat(0): MySQL server reconnect was unsuccessful"
mysql server log: [error.log](https://github.com/devzspy/GameSpy-Openspy-Core/files/4102550/error.log)

how did i need to reconfigure my mysql server?

**Comment by devzspy** [comment]
Do you have a user called `openspy` configured? 

Did you import the SQL Databases / tables?

I don't believe I have everything uploaded db/table wise which I need to fix.

**Comment by jackcaver** [comment]
"Do you have a user called openspy configured?" - yes
"Did you import the SQL Databases / tables?" - yes, but "Matrix" db was imported from other gamespy emulator

**Comment by devzspy** [comment]
@jackcaver I just uploaded my matrix sql db. Give that a shot or compare the two to see what's missing.

**Comment by jackcaver** [comment]
still get an error when i trying to compile it:
> from cfuncs.cpp:2:
main.h:45:10: fatal error: lua.h: No such file or directory
 #include <lua.h>
          ^~~~~~~
compilation terminated.
In file included from handler.h:3:0,
                 from handler.cpp:2:
main.h:45:10: fatal error: lua.h: No such file or directory
 #include <lua.h>
          ^~~~~~~
compilation terminated.
In file included from main.cpp:1:0:
main.h:45:10: fatal error: lua.h: No such file or directory
 #include <lua.h>
          ^~~~~~~
compilation terminated.
In file included from statsmanage.h:1:0,
                 from statsmanage.cpp:1:
main.h:45:10: fatal error: lua.h: No such file or directory
 #include <lua.h>
          ^~~~~~~
compilation terminated.
Makefile:2: recipe for target 'start' failed
make[1]: *** [start] Error 1
make[1]: Leaving directory '/home/jackcaver/GameSpy-Openspy-Core-master/legacystatsprocessor'
Makefile:2: recipe for target 'start' failed
make: *** [start] Error 2 
>                 
and now i get this error when i trying to run it without compilation:
> ./openspy: error while loading shared libraries: libmysqlclient.so.18: cannot open shared object file: No such file or directory

**Comment by devzspy** [comment]
If I remember correctly, I borrowed the instructions from https://github.com/bads-tm-archive/swine_gamespy/wiki/Building-and-Running

I am in contact with the original developer of this version of OpenSpy. However, he is currently working on a newer version which will be more stable, have API endpoints, utilize python, AWS, etc.

Most of the work I've done with this is to restore the chat servers and services to what they used to be when logging into GameSpy Arcade. The actual core functionality I have nothing to do with on this repo. I've been passing along my findings to the main developer. You can find the newer in development project at https://discord.gg/FWeqTPQ

**Comment by jackcaver** [comment]
ok, now i have same error on compilation, but mysql error was replaced by this:
![2020-02-05_05-41-04](https://user-images.githubusercontent.com/50882080/73797675-e8a82e00-47da-11ea-894a-398d2663adaa.png)

**Comment by devzspy** [comment]
Usually related to the peerchat service not working or bad profile/account in the database. May also be you haven't updated your hosts file to point at your server. @jackcaver

**Comment by jackcaver** [comment]
Hosts file was updated and account exists in database, because I used login manager to login

**Comment by devzspy** [comment]
Anything in your terminal window error wise?

**Comment by jackcaver** [comment]
![2020-02-11_14-58-49](https://user-images.githubusercontent.com/50882080/74226369-a2753200-4ce6-11ea-93df-7f8a55a7aa4e.png)

**Comment by devzspy** [comment]
@jackcaver not sure how important your password is if using a real one. That md5 right after `/proof/` is your password. Might wanna blur that out or delete the image entirely.

I believe there should be one more line that doesn't appear. I don't have my server setup anymore to check. 

I can try to get it setup at a later time (in like 15 hours) when I am home from work. Although I need to start packing up my stuff as I am moving.

**Comment by jackcaver** [comment]
i can try to set a new user for ssh if it need

**Comment by jackcaver** [comment]
ok, i can connect to peerchat from mobile irc client, but i can't do this on pc or gamespy arcade app
![Screenshot_2020-02-14-02-13-09-160_io mrarm irc](https://user-images.githubusercontent.com/50882080/74476815-5b4c9400-4ed4-11ea-984a-94e0543f321d.jpg)

 also i can't execute /oper command because i'm getting this error
![2020-02-14_02-21-43](https://user-images.githubusercontent.com/50882080/74476888-80410700-4ed4-11ea-9352-f3c8e389151d.png)

**Comment by devzspy** [comment]
I don't have access to my computer anymore as I had to pack it up. That being said the screenshot you posted shows you are missing a UDF (User Defined Function). I can try to see if I have it saved anywhere that is accessible on my phone.

**Comment by jackcaver** [comment]
Ok, i returned to the first error by compiling and importing this  https://github.com/devzspy/GameSpy-Openspy-Core/tree/master/udf/Matrix udf_matrixqueue function 
![IMG_20200214_103706](https://user-images.githubusercontent.com/50882080/74504717-4e08c700-4f1f-11ea-81f0-eead144af57b.jpg)
mysql server reports about same error as in first time i get this error

**Comment by devzspy** [comment]
It's hard to troubleshoot why you're losing the database connection. I believe I ran into that issue but I can't recall what i did to fix it.

I know I had issues also with creating new users/profiles. I actually would have to copy an existing working user/profile and then modify it in the tables to make things work.

**Comment by jackcaver** [comment]
> I know I had issues also with creating new users/profiles. I actually would have to copy an existing working user/profile and then modify it in the tables to make things work.
>          
After i imported "GameTracker" database i'm also get an issue with profile creation, but i changed default values in order to get a profile using gamespy arcade app

**Comment by devzspy** [comment]
Seems like you got it working. Sorry for the very late response. Was moving, getting settled in new home/job and then the covid-19 stuff hit.
